---
{{- if .Values.ingress.enabled -}}
{{- $replicas := int .Values.replicas }}
{{- $fullName := include "apache-nifi.fullname" $ -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "apache-nifi.fullname" $ }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "apache-nifi.name" . }}
    app.kubernetes.io/part-of: nifi
    app.kubernetes.io/version: {{ .Chart.Version }}
    helm.sh/chart: {{ include "apache-nifi.chart" . }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
{{- end }}
  tls:
  - hosts:
    {{- range $i := until $replicas }}
    - {{ printf "node%d-%s" $i $.Values.clusterName }}
    {{- end }}
    - {{ .Values.clusterName }}
    {{- range $host := .Values.extraHosts }}
    - {{ $host }}
    {{- end }}
    {{- if .Values.ingress.secretName }}
    secretName: {{ .Values.ingress.secretName }}
    {{- end }}
  rules:
  - host: {{ .Values.clusterName }}
    http:
      paths:
      - path: {{ .Values.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ $fullName }}-ingress
            port:
              number: {{ .Values.service.httpsPort }}
  {{- range $host := .Values.extraHosts }}
  - host: {{ $host }}
    http:
      paths:
      - path: {{ $.Values.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ $fullName }}-ingress
            port:
              number: {{ $.Values.service.httpsPort }}
  {{- end }}
  {{- range $i := until $replicas }}
  - host: {{ printf "node%d-%s" $i $.Values.clusterName }}
    http:
      paths:
      - path: {{ $.Values.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ printf "nifi-%d" $i }}-ingress
            port:
              number: {{ $.Values.properties.httpsPort }}
  {{- end }}
{{- end }}
