{{- if .Values.sts.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "apache-nifi.name" . }}
    app.kubernetes.io/part-of: nifi
    app.kubernetes.io/version: {{ .Chart.Version }}
    helm.sh/chart: {{ include "apache-nifi.chart" . }}
  name: {{ include "apache-nifi.serviceAccountName" . }}
  {{- with .Values.sts.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
